package com.homework.solarvillage;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class NewOrder implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Electrical Submit")
	private java.lang.String electricalSubmit;
	@org.kie.api.definition.type.Label("Structural Submit")
	private java.lang.String structuralSubmit;
	@org.kie.api.definition.type.Label("Resident Name")
	private java.lang.String residentName;
	@org.kie.api.definition.type.Label("Residence Type")
	private java.lang.Character typeResidence;
	@org.kie.api.definition.type.Label("Status")
	private java.lang.String status;

	@org.kie.api.definition.type.Label("HOA Approval")
	private java.lang.Character hoaApproval;

	@org.kie.api.definition.type.Label(value = "Revisor Status")
	private java.lang.Character revisorStatus;

	public NewOrder() {
	}

	public java.lang.String getElectricalSubmit() {
		return this.electricalSubmit;
	}

	public void setElectricalSubmit(java.lang.String electricalSubmit) {
		this.electricalSubmit = electricalSubmit;
	}

	public java.lang.String getStructuralSubmit() {
		return this.structuralSubmit;
	}

	public void setStructuralSubmit(java.lang.String structuralSubmit) {
		this.structuralSubmit = structuralSubmit;
	}

	public java.lang.String getResidentName() {
		return this.residentName;
	}

	public void setResidentName(java.lang.String residentName) {
		this.residentName = residentName;
	}

	public java.lang.Character getTypeResidence() {
		return this.typeResidence;
	}

	public void setTypeResidence(java.lang.Character typeResidence) {
		this.typeResidence = typeResidence;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.Character getHoaApproval() {
		return this.hoaApproval;
	}

	public void setHoaApproval(java.lang.Character hoaApproval) {
		this.hoaApproval = hoaApproval;
	}

	public java.lang.Character getRevisorStatus() {
		return this.revisorStatus;
	}

	public void setRevisorStatus(java.lang.Character revisorStatus) {
		this.revisorStatus = revisorStatus;
	}

	public NewOrder(java.lang.String electricalSubmit,
			java.lang.String structuralSubmit, java.lang.String residentName,
			java.lang.Character typeResidence, java.lang.String status,
			java.lang.Character hoaApproval, java.lang.Character revisorStatus) {
		this.electricalSubmit = electricalSubmit;
		this.structuralSubmit = structuralSubmit;
		this.residentName = residentName;
		this.typeResidence = typeResidence;
		this.status = status;
		this.hoaApproval = hoaApproval;
		this.revisorStatus = revisorStatus;
	}

}