package com.homework.solarvillage;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RequestSubmit implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "pid")
	private java.lang.Integer pid;

	public RequestSubmit() {
	}

	public java.lang.Integer getPid() {
		return this.pid;
	}

	public void setPid(java.lang.Integer pid) {
		this.pid = pid;
	}

	public RequestSubmit(java.lang.Integer pid) {
		this.pid = pid;
	}

}