package com.homework.solarvillage;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ResponseStructuralStatus implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ResponseStructuralStatus() {
    }




}