package com.homework.solarvillage;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ResponseElectricalStatus implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("ID")
	private java.lang.Integer id;
	@org.kie.api.definition.type.Label("Status")
	private java.lang.String status;

	public ResponseElectricalStatus() {
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public ResponseElectricalStatus(java.lang.Integer id,
			java.lang.String status) {
		this.id = id;
		this.status = status;
	}

}